### ISSUE TITLE
找不到依赖，已经上传了么

### ISSUE THREAD

**Issue by shenshizhong** [gaoneng102/AutoScrollBackLayout#2]
Error:(29, 14) Failed to resolve: com.gaoneng.library:autoscrollbacklayout:1.1.0

**Comment by gaoneng102** [comment]
@shenshizhong 不好意思，上传了，但是忘记同步到jcenter了，多谢提醒。

**Comment by Joeyscat** [comment]
请问这个问题解决了吗,我还是用不了
Error:(29, 14) Failed to resolve: com.gaoneng.library:autoscrollbacklayout:1.1.0

**Comment by gaoneng102** [comment]
@Joeyscat 依赖已经通过审核了，现在可以用了

**Comment by shenshizhong** [comment]
@gaoneng102 嗯嗯，现在可以用了，谢谢。
 @Joeyscat    直接粘贴下面这个就可以了
 compile ('com.gaoneng.library:autoscrollbacklayout:1.1.1'){
        exclude group:'com.android.support',module:'recyclerview-v7'
    }
